name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 登录到 DockerHub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # 构建并推送多架构镜像
      - name: Build and push multi-architecture Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" == "main" ]; then
            docker buildx build . \
              --file Dockerfile \
              --platform linux/amd64,linux/arm64 \
              --tag ${{ secrets.DOCKER_USERNAME }}/emailforward:$(date +%Y%m%d) \
              --tag ${{ secrets.DOCKER_USERNAME }}/emailforward:latest \
              --push
          else
            docker buildx build . \
              --file Dockerfile \
              --platform linux/amd64,linux/arm64 \
              --tag ${{ secrets.DOCKER_USERNAME }}/emailforward:$BRANCH_NAME \
              --push
