name: Docker Image CI

on:
  # push:
  #     branches:
  #       - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" == "main" ]; then
            docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/emailforward:$(date +%Y%m%d)
            docker push ${{ secrets.DOCKER_USERNAME }}/emailforward:$(date +%Y%m%d)
            docker tag ${{ secrets.DOCKER_USERNAME }}/emailforward:$(date +%Y%m%d) ${{ secrets.DOCKER_USERNAME }}/emailforward:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/emailforward:latest
          else
            docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/emailforward:$BRANCH_NAME
            docker push ${{ secrets.DOCKER_USERNAME }}/emailforward:$BRANCH_NAME
          fi
